server:
  port: ${SERVER_PORT:8080}
#  servlet:
#    context-path: /orders-management/orders-api/v1
spring:
  application:
    name: demo-microservice1
  jpa:
    database: postgresql
    show-sql: ${SHOW_SQL_COMMANDS:true}
    generate-ddl: ${GENERATE_DDL:true}
  datasource:
    url: ${JPA_DATASOURCE_URL:jdbc:postgresql://localhost:5432/orders}
    password: ${DB_PASSWORD:mysecretpassword}
    hikari:
      username: ${DB_USERNAME:postgres}



microservices:
- ordersMicroservice:
    urlWithPort: ${SERVER_PORT_ORDERS:localhost:8081}
    endpoints:
      common: /orders-management/orders-infra/v1/order
      get:
      getAll:
      post:
- cachingMicroservice:
    urlWithPort: ${SERVER_PORT_CACHING:localhost:8081}
    endpoints:
      get: /orders-management/orders-caching/v1/caching

